export const backgroundRegistry = {
  bg01: {
    id: 'bg01',
    label: 'Countdown Stage',
    videoPath: '/assets/backgrounds/video/bg01-countdown-stage-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg01-countdown-stage-loop.jpg',
    fallbackType: 'countdown-stage',
    referenceScene: 1,
    referenceFile: '01_live_stream_starting_soon_countdown.png',
    notes: 'Clean branded countdown environment with center platform glow, equalizer accents, and ambient broadcast energy.',
  },
  bg02: {
    id: 'bg02',
    label: 'Music Visualizer',
    videoPath: '/assets/backgrounds/video/bg02-music-visualizer-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg02-music-visualizer-loop.jpg',
    fallbackType: 'music-visualizer',
    referenceScene: 2,
    referenceFile: '02_welcome_music_visualizer.png',
    notes: 'Energetic waveform/equalizer visualizer environment.',
  },
  bg03: {
    id: 'bg03',
    label: 'Presenter Studio',
    videoPath: '/assets/backgrounds/video/bg03-presenter-studio-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg03-presenter-studio-loop.jpg',
    fallbackType: 'presenter-studio',
    referenceScene: 3,
    referenceFile: '03_host_standby_camera.png',
    notes: 'Studio/presenter environment with subtle ambient light and display-screen atmosphere.',
  },
  bg04: {
    id: 'bg04',
    label: 'Brand Stinger',
    videoPath: '/assets/backgrounds/video/bg04-brand-stinger-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg04-brand-stinger-loop.jpg',
    fallbackType: 'brand-stinger',
    referenceScene: 4,
    referenceFile: '04_grand_opening_stinger.png',
    notes: 'Cinematic brand reveal atmosphere and dramatic light sweeps.',
  },
  bg05: {
    id: 'bg05',
    label: 'Explainer Clean Wave',
    videoPath: '/assets/backgrounds/video/bg05-explainer-clean-wave-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg05-explainer-clean-wave-loop.jpg',
    fallbackType: 'explainer-clean-wave',
    referenceScene: 6,
    referenceFile: '06_what_is_bema_hub.png',
    notes: 'Clean white/blue explainer environment with soft waveforms and subtle broadcast motion.',
  },
  bg06: {
    id: 'bg06',
    label: 'Dashboard / Product Walkthrough',
    videoPath: '/assets/backgrounds/video/bg06-dashboard-product-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg06-dashboard-product-loop.jpg',
    fallbackType: 'dashboard-product',
    referenceScene: 16,
    referenceFile: '16_bema_hub_walkthrough_home_dashboard.png',
    notes: 'Product-walkthrough and dashboard-oriented environment with cleaner tech ambience.',
  },
  bg07: {
    id: 'bg07',
    label: 'Enrollment CTA',
    videoPath: '/assets/backgrounds/video/bg07-enrollment-cta-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg07-enrollment-cta-loop.jpg',
    fallbackType: 'enrollment-cta',
    referenceScene: 14,
    referenceFile: '14_live_enrollment_invitation.png',
    notes: 'Bright action-oriented enrollment environment optimized for QR and CTA overlays.',
  },
  bg08: {
    id: 'bg08',
    label: 'Closing Hold',
    videoPath: '/assets/backgrounds/video/bg08-closing-hold-loop.mp4',
    posterPath: '/assets/backgrounds/posters/bg08-closing-hold-loop.jpg',
    fallbackType: 'closing-hold',
    referenceScene: 35,
    referenceFile: '35_thank_you_and_next_steps.png',
    notes: 'Calm closing/end-card atmosphere with softer energy and elegant finish.',
  },
}
